import { BugMatrixRule, BugMatrixTheme } from '@wiki-race/shared';

export const THEMES: BugMatrixTheme[] = [
  { id: 'cantine', label: 'À la cantine' },
  { id: 'recre', label: 'Dans la cour de récré' },
  { id: 'vacances', label: 'En vacances à la mer' },
  { id: 'pyjama', label: 'Soirée pyjama' },
  { id: 'parc', label: "Au parc d'attractions" },
  { id: 'bureau', label: 'Au bureau un lundi matin' },
  { id: 'dentiste', label: 'Chez le dentiste' },
  { id: 'mariage', label: 'À un mariage' },
  { id: 'metro', label: 'Coincé dans le métro' },
  { id: 'supermarche', label: 'Au supermarché' },
  { id: 'camping', label: 'En camping sous la pluie' },
  { id: 'ski', label: 'À la station de ski' },
  { id: 'pharmacie', label: 'À la pharmacie' },
  { id: 'cinema', label: 'Au cinéma' },
  { id: 'plage', label: 'À la plage en plein été' },
  { id: 'aeroport', label: "À l'aéroport en retard" },
  { id: 'restaurant', label: 'Au restaurant un samedi soir' },
  { id: 'salle-sport', label: 'À la salle de sport' },
  { id: 'reunion-famille', label: 'À une réunion de famille' },
  { id: 'concert', label: 'À un concert en plein air' },
  { id: 'piscine', label: 'À la piscine municipale' },
  { id: 'manif', label: 'À une manifestation' },
  { id: 'covoiturage', label: 'Dans un covoiturage de 8h' },
  { id: 'salle-attente', label: 'En salle d’attente' },
  { id: 'fete-foraine', label: 'À la fête foraine' },
];

export const RULES: BugMatrixRule[] = [
  // FORM
  { id: 'form-number', label: 'Tu dois TOUJOURS glisser un nombre dans tes phrases.', category: 'FORM', difficulty: 'EASY' },
  { id: 'form-en-fait', label: 'Tu dois TOUJOURS commencer tes phrases par "En fait,".', category: 'FORM', difficulty: 'EASY' },
  { id: 'form-ben-deja', label: 'Tu dois TOUJOURS commencer tes phrases par "Ben déjà".', category: 'FORM', difficulty: 'EASY' },
  { id: 'form-tu-vois', label: 'Tu dois TOUJOURS finir tes phrases par "tu vois".', category: 'FORM', difficulty: 'EASY' },
  { id: 'form-cest-sur', label: 'Tu dois TOUJOURS finir tes phrases par "c’est sûr".', category: 'FORM', difficulty: 'EASY' },
  { id: 'form-no-r', label: 'Tu n’as PAS le droit d’utiliser la lettre R.', category: 'FORM', difficulty: 'HARD' },
  { id: 'form-no-s', label: 'Tu n’as PAS le droit d’utiliser la lettre S.', category: 'FORM', difficulty: 'HARD' },
  { id: 'form-repeat', label: 'Tu dois RÉPÉTER une partie de la phrase de la personne précédente.', category: 'FORM', difficulty: 'MEDIUM' },
  { id: 'form-question', label: 'Tu dois TERMINER chaque phrase par une question.', category: 'FORM', difficulty: 'MEDIUM' },
  { id: 'form-franchement', label: 'Tu dois TOUJOURS commencer par "Franchement,".', category: 'FORM', difficulty: 'EASY' },
  { id: 'form-short', label: 'Tu dois répondre en MOINS de 6 mots.', category: 'FORM', difficulty: 'MEDIUM' },

  // TONE
  { id: 'tone-positive', label: 'Tu dois être HYPER POSITIF, même sur les trucs nuls.', category: 'TONE', difficulty: 'EASY' },
  { id: 'tone-negative', label: 'Tu dois TOUT trouver nul, même les trucs cool.', category: 'TONE', difficulty: 'EASY' },
  { id: 'tone-dramatic', label: 'Tu dois parler comme si TOUT était ULTRA dramatique.', category: 'TONE', difficulty: 'EASY' },
  { id: 'tone-exagerer', label: 'Tu dois TOUJOURS exagérer (tout est trop, immense, incroyable…).', category: 'TONE', difficulty: 'EASY' },
  { id: 'tone-fear', label: 'Tu dois parler comme si tu avais PEUR de tout.', category: 'TONE', difficulty: 'MEDIUM' },
  { id: 'tone-bored', label: 'Tu dois parler comme si tu t’ennuyais à MORT.', category: 'TONE', difficulty: 'EASY' },
  { id: 'tone-detester', label: 'Tu dois faire SEMBLANT de détester ce que les autres aiment.', category: 'TONE', difficulty: 'MEDIUM' },
  { id: 'tone-snob', label: 'Tu dois parler comme si tu étais un grand SNOB.', category: 'TONE', difficulty: 'MEDIUM' },
  { id: 'tone-whisper', label: 'Tu dois parler comme si tu disais un SECRET.', category: 'TONE', difficulty: 'MEDIUM' },

  // CONTENT
  { id: 'content-food', label: 'Tu dois mentionner une NOURRITURE dans chaque phrase.', category: 'CONTENT', difficulty: 'EASY' },
  { id: 'content-animal', label: 'Tu dois mentionner un ANIMAL dans chaque phrase.', category: 'CONTENT', difficulty: 'EASY' },
  { id: 'content-competition', label: 'Tu dois parler comme si tout était une COMPÉTITION.', category: 'CONTENT', difficulty: 'MEDIUM' },
  { id: 'content-grandma', label: 'Tu dois caser ta GRAND-MÈRE dans chaque réponse.', category: 'CONTENT', difficulty: 'MEDIUM' },
  { id: 'content-money', label: 'Tu dois parler d’ARGENT dans chaque réponse.', category: 'CONTENT', difficulty: 'MEDIUM' },
  { id: 'content-meteo', label: 'Tu dois mentionner la MÉTÉO dans chaque réponse.', category: 'CONTENT', difficulty: 'EASY' },
  { id: 'content-color', label: 'Tu dois citer une COULEUR dans chaque phrase.', category: 'CONTENT', difficulty: 'EASY' },
  { id: 'content-chiffre-rond', label: 'Tu dois citer un OBJET concret dans chaque phrase.', category: 'CONTENT', difficulty: 'MEDIUM' },
  { id: 'content-celeb', label: 'Tu dois caser le nom d’une CÉLÉBRITÉ dans tes phrases.', category: 'CONTENT', difficulty: 'HARD' },
];

export const QUESTIONS: string[] = [
  'Qu’est-ce que tu fais en premier dans cette situation ?',
  'Qu’est-ce qui te plaît le moins ici ?',
  'Avec qui tu préfères être dans ce contexte ?',
  'Qu’est-ce qui te stresse le plus ?',
  'Qu’est-ce que tu emporterais avec toi ?',
  'Si tu pouvais changer un truc, ce serait quoi ?',
  'Qu’est-ce que tu manges/bois là pour tenir ?',
  'À quelle heure tu arrives, en général ?',
  'Quel est le pire moment selon toi ?',
  'Quel est le meilleur moment selon toi ?',
  'Comment tu t’habilles pour ça ?',
  'Tu y viens souvent ?',
  'Qu’est-ce que tu racontes à tes potes après ?',
  'Si tu devais y emmener quelqu’un, ce serait qui ?',
  'C’est quoi ton petit rituel ici ?',
  'Qu’est-ce qui te ferait fuir tout de suite ?',
  'Tu préfères y être seul ou en groupe, et pourquoi ?',
  'Quel est ton plan B si ça tourne mal ?',
  'Tu fais quoi pour passer le temps ?',
  'Quel souvenir tu en gardes en général ?',
  'Tu as une anecdote bizarre liée à ça ?',
  'Tu dirais que c’est plutôt cool ou plutôt galère ?',
  'Qu’est-ce que tu remarques en premier en arrivant ?',
  'Tu as déjà voulu partir avant la fin ?',
  'Quelle musique tu écouterais là, si tu pouvais ?',
  'Tu prends des photos ou pas du tout ?',
  'Tu serais plutôt à fond ou en mode discret ?',
  'Qu’est-ce que tu refuserais de faire ici ?',
  'C’est quoi le truc cliché qui se passe à chaque fois ?',
  'Tu repartirais avec quoi en souvenir ?',
  'Tu penses à quoi quand tu y vas ?',
  'Qu’est-ce qu’on te dit toujours là-bas ?',
  'Si c’était un film, ce serait quoi le titre ?',
  'Tu as déjà fait n’importe quoi dans cette situation ?',
  'Qu’est-ce que tu n’oserais jamais avouer ici ?',
  'Tu y vas plutôt par obligation ou par envie ?',
  'C’est quoi le truc qui t’énerve à coup sûr ?',
  'Qu’est-ce qui te ferait revenir ?',
  'Quelle question tu poserais aux autres ?',
  'Tu crois que les autres te jugent comment dans ce contexte ?',
];
