export interface WordEntry {
  word: string;
  category: string;
}

// 240+ mots répartis sur 6 catégories
export const WORD_POOL: WordEntry[] = [
  // objets (40)
  { word: 'chaise', category: 'objets' },
  { word: 'miroir', category: 'objets' },
  { word: 'lampe', category: 'objets' },
  { word: 'table', category: 'objets' },
  { word: 'clé', category: 'objets' },
  { word: 'sac', category: 'objets' },
  { word: 'livre', category: 'objets' },
  { word: 'crayon', category: 'objets' },
  { word: 'horloge', category: 'objets' },
  { word: 'bougie', category: 'objets' },
  { word: 'coussin', category: 'objets' },
  { word: 'rideau', category: 'objets' },
  { word: 'tasse', category: 'objets' },
  { word: 'ciseaux', category: 'objets' },
  { word: 'tiroir', category: 'objets' },
  { word: 'lunettes', category: 'objets' },
  { word: 'parapluie', category: 'objets' },
  { word: 'valise', category: 'objets' },
  { word: 'telephone', category: 'objets' },
  { word: 'casque', category: 'objets' },
  { word: 'carnet', category: 'objets' },
  { word: 'bouteille', category: 'objets' },
  { word: 'cadenas', category: 'objets' },
  { word: 'filet', category: 'objets' },
  { word: 'chariot', category: 'objets' },
  { word: 'bague', category: 'objets' },
  { word: 'montre', category: 'objets' },
  { word: 'boite', category: 'objets' },
  { word: 'corde', category: 'objets' },
  { word: 'tapis', category: 'objets' },
  { word: 'bureau', category: 'objets' },
  { word: 'marteau', category: 'objets' },
  { word: 'pinceau', category: 'objets' },
  { word: 'echelle', category: 'objets' },
  { word: 'balai', category: 'objets' },
  { word: 'fourche', category: 'objets' },
  { word: 'cadre', category: 'objets' },
  { word: 'drapeau', category: 'objets' },
  { word: 'coffre', category: 'objets' },
  { word: 'cloche', category: 'objets' },

  // animaux (40)
  { word: 'lion', category: 'animaux' },
  { word: 'chat', category: 'animaux' },
  { word: 'chien', category: 'animaux' },
  { word: 'aigle', category: 'animaux' },
  { word: 'dauphin', category: 'animaux' },
  { word: 'renard', category: 'animaux' },
  { word: 'loup', category: 'animaux' },
  { word: 'ours', category: 'animaux' },
  { word: 'elephant', category: 'animaux' },
  { word: 'girafe', category: 'animaux' },
  { word: 'tigre', category: 'animaux' },
  { word: 'perroquet', category: 'animaux' },
  { word: 'serpent', category: 'animaux' },
  { word: 'papillon', category: 'animaux' },
  { word: 'abeille', category: 'animaux' },
  { word: 'baleine', category: 'animaux' },
  { word: 'requin', category: 'animaux' },
  { word: 'singe', category: 'animaux' },
  { word: 'zebre', category: 'animaux' },
  { word: 'mouton', category: 'animaux' },
  { word: 'vache', category: 'animaux' },
  { word: 'cochon', category: 'animaux' },
  { word: 'lapin', category: 'animaux' },
  { word: 'grenouille', category: 'animaux' },
  { word: 'tortue', category: 'animaux' },
  { word: 'hibou', category: 'animaux' },
  { word: 'corbeau', category: 'animaux' },
  { word: 'pingouin', category: 'animaux' },
  { word: 'flamant', category: 'animaux' },
  { word: 'crocodile', category: 'animaux' },
  { word: 'poulpe', category: 'animaux' },
  { word: 'pieuvre', category: 'animaux' },
  { word: 'cerf', category: 'animaux' },
  { word: 'sanglier', category: 'animaux' },
  { word: 'ecureuil', category: 'animaux' },
  { word: 'herisson', category: 'animaux' },
  { word: 'panda', category: 'animaux' },
  { word: 'koala', category: 'animaux' },
  { word: 'colibri', category: 'animaux' },
  { word: 'mante', category: 'animaux' },

  // lieux (40)
  { word: 'plage', category: 'lieux' },
  { word: 'foret', category: 'lieux' },
  { word: 'montagne', category: 'lieux' },
  { word: 'desert', category: 'lieux' },
  { word: 'ville', category: 'lieux' },
  { word: 'village', category: 'lieux' },
  { word: 'marche', category: 'lieux' },
  { word: 'jardin', category: 'lieux' },
  { word: 'parc', category: 'lieux' },
  { word: 'gare', category: 'lieux' },
  { word: 'aeroport', category: 'lieux' },
  { word: 'port', category: 'lieux' },
  { word: 'musee', category: 'lieux' },
  { word: 'bibliotheque', category: 'lieux' },
  { word: 'stade', category: 'lieux' },
  { word: 'cinema', category: 'lieux' },
  { word: 'hopital', category: 'lieux' },
  { word: 'ecole', category: 'lieux' },
  { word: 'eglise', category: 'lieux' },
  { word: 'chateau', category: 'lieux' },
  { word: 'prison', category: 'lieux' },
  { word: 'phare', category: 'lieux' },
  { word: 'caverne', category: 'lieux' },
  { word: 'volcan', category: 'lieux' },
  { word: 'glacier', category: 'lieux' },
  { word: 'ile', category: 'lieux' },
  { word: 'lac', category: 'lieux' },
  { word: 'riviere', category: 'lieux' },
  { word: 'ocean', category: 'lieux' },
  { word: 'prairie', category: 'lieux' },
  { word: 'savane', category: 'lieux' },
  { word: 'toundra', category: 'lieux' },
  { word: 'marais', category: 'lieux' },
  { word: 'falaise', category: 'lieux' },
  { word: 'colline', category: 'lieux' },
  { word: 'vallee', category: 'lieux' },
  { word: 'tunnel', category: 'lieux' },
  { word: 'pont', category: 'lieux' },
  { word: 'rue', category: 'lieux' },
  { word: 'place', category: 'lieux' },

  // nourriture (40)
  { word: 'pizza', category: 'nourriture' },
  { word: 'pain', category: 'nourriture' },
  { word: 'fromage', category: 'nourriture' },
  { word: 'chocolat', category: 'nourriture' },
  { word: 'sucre', category: 'nourriture' },
  { word: 'miel', category: 'nourriture' },
  { word: 'citron', category: 'nourriture' },
  { word: 'tomate', category: 'nourriture' },
  { word: 'fraise', category: 'nourriture' },
  { word: 'pomme', category: 'nourriture' },
  { word: 'banane', category: 'nourriture' },
  { word: 'noix', category: 'nourriture' },
  { word: 'riz', category: 'nourriture' },
  { word: 'soupe', category: 'nourriture' },
  { word: 'gateau', category: 'nourriture' },
  { word: 'tarte', category: 'nourriture' },
  { word: 'salade', category: 'nourriture' },
  { word: 'poulet', category: 'nourriture' },
  { word: 'poisson', category: 'nourriture' },
  { word: 'oeuf', category: 'nourriture' },
  { word: 'beurre', category: 'nourriture' },
  { word: 'creme', category: 'nourriture' },
  { word: 'cafe', category: 'nourriture' },
  { word: 'the', category: 'nourriture' },
  { word: 'jus', category: 'nourriture' },
  { word: 'chips', category: 'nourriture' },
  { word: 'bonbon', category: 'nourriture' },
  { word: 'glace', category: 'nourriture' },
  { word: 'crepe', category: 'nourriture' },
  { word: 'croissant', category: 'nourriture' },
  { word: 'baguette', category: 'nourriture' },
  { word: 'champignon', category: 'nourriture' },
  { word: 'oignon', category: 'nourriture' },
  { word: 'ail', category: 'nourriture' },
  { word: 'poivre', category: 'nourriture' },
  { word: 'cannelle', category: 'nourriture' },
  { word: 'vanille', category: 'nourriture' },
  { word: 'framboise', category: 'nourriture' },
  { word: 'cerise', category: 'nourriture' },
  { word: 'mangue', category: 'nourriture' },

  // émotions (40)
  { word: 'joie', category: 'emotions' },
  { word: 'peur', category: 'emotions' },
  { word: 'colere', category: 'emotions' },
  { word: 'tristesse', category: 'emotions' },
  { word: 'surprise', category: 'emotions' },
  { word: 'amour', category: 'emotions' },
  { word: 'honte', category: 'emotions' },
  { word: 'fierte', category: 'emotions' },
  { word: 'jalousie', category: 'emotions' },
  { word: 'ennui', category: 'emotions' },
  { word: 'curiosite', category: 'emotions' },
  { word: 'gratitude', category: 'emotions' },
  { word: 'esperance', category: 'emotions' },
  { word: 'nostalgie', category: 'emotions' },
  { word: 'anxiete', category: 'emotions' },
  { word: 'solitude', category: 'emotions' },
  { word: 'calme', category: 'emotions' },
  { word: 'courage', category: 'emotions' },
  { word: 'confiance', category: 'emotions' },
  { word: 'regret', category: 'emotions' },
  { word: 'enthousiasme', category: 'emotions' },
  { word: 'indifference', category: 'emotions' },
  { word: 'tendresse', category: 'emotions' },
  { word: 'degout', category: 'emotions' },
  { word: 'admiration', category: 'emotions' },
  { word: 'impatience', category: 'emotions' },
  { word: 'soulagement', category: 'emotions' },
  { word: 'desespoir', category: 'emotions' },
  { word: 'euphorie', category: 'emotions' },
  { word: 'melancolie', category: 'emotions' },
  { word: 'timidite', category: 'emotions' },
  { word: 'genereux', category: 'emotions' },
  { word: 'compassion', category: 'emotions' },
  { word: 'envie', category: 'emotions' },
  { word: 'rancune', category: 'emotions' },
  { word: 'paix', category: 'emotions' },
  { word: 'bonheur', category: 'emotions' },
  { word: 'excitation', category: 'emotions' },
  { word: 'irritation', category: 'emotions' },
  { word: 'satisfaction', category: 'emotions' },

  // nature (40)
  { word: 'soleil', category: 'nature' },
  { word: 'lune', category: 'nature' },
  { word: 'etoile', category: 'nature' },
  { word: 'nuage', category: 'nature' },
  { word: 'pluie', category: 'nature' },
  { word: 'vent', category: 'nature' },
  { word: 'neige', category: 'nature' },
  { word: 'foudre', category: 'nature' },
  { word: 'arc-en-ciel', category: 'nature' },
  { word: 'brouillard', category: 'nature' },
  { word: 'tornade', category: 'nature' },
  { word: 'tremblement', category: 'nature' },
  { word: 'tsunami', category: 'nature' },
  { word: 'aurore', category: 'nature' },
  { word: 'rosee', category: 'nature' },
  { word: 'givre', category: 'nature' },
  { word: 'grelons', category: 'nature' },
  { word: 'vague', category: 'nature' },
  { word: 'maree', category: 'nature' },
  { word: 'corail', category: 'nature' },
  { word: 'arbre', category: 'nature' },
  { word: 'fleur', category: 'nature' },
  { word: 'graine', category: 'nature' },
  { word: 'racine', category: 'nature' },
  { word: 'feuille', category: 'nature' },
  { word: 'branche', category: 'nature' },
  { word: 'mousse', category: 'nature' },
  { word: 'champignon', category: 'nature' },
  { word: 'roc', category: 'nature' },
  { word: 'sable', category: 'nature' },
  { word: 'boue', category: 'nature' },
  { word: 'terre', category: 'nature' },
  { word: 'lave', category: 'nature' },
  { word: 'cendre', category: 'nature' },
  { word: 'gaz', category: 'nature' },
  { word: 'cristal', category: 'nature' },
  { word: 'diamant', category: 'nature' },
  { word: 'ivoire', category: 'nature' },
  { word: 'ambre', category: 'nature' },
  { word: 'obsidienne', category: 'nature' },
];

export function getWordPool(category: string): string[] {
  const entries = category === 'all' ? WORD_POOL : WORD_POOL.filter((w) => w.category === category);
  return entries.map((w) => w.word);
}

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export const DEFAULT_TELEPATHIE_SETTINGS = {
  totalManches: 5,
  maxSousRounds: 10,
  roundTimerSeconds: 30,
};
